hugoblox:
  schema: "2.0"
  identity:
    name: Josh McCamley - Technical Game Designer
    type: person
    tagline: Co-Director and Technical Designer | Mad Moon Studios | Ulster University
    description: ""
  theme:
    mode: dark
    pack: retro
    colors:
      primary: "#e05e5e"
      secondary: ""
      neutral: ""
    colors_light:
      primary: ""
    colors_dark:
      primary: ""
      secondary: ""
      neutral: "#476ed3"
    surfaces:
      header:
        background: "#1c253a"
      footer:
        background: "#1c253a"
      background: "#1c253a"
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: rounded
  header:
    enable: true
    style: navbar
    sticky: true
    align: right
    search: true
    theme_toggle: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: false
  search:
    enable: true
